FIND_PATH(LIBPUGIXML_INCLUDE_DIR pugixml.h)

SET(LIBPUGIXML_NAMES ${LIBPUGIXML_NAMES} pugixml libpugixml)
FIND_LIBRARY(LIBPUGIXML_LIBRARY NAMES ${LIBPUGIXML_NAMES} PATH)

IF(LIBPUGIXML_INCLUDE_DIR AND LIBPUGIXML_LIBRARY)
	SET(LIBPUGIXML_FOUND TRUE)
ENDIF()

IF(LIBPUGIXML_FOUND)
	IF(NOT LibPugiXml_FIND_QUIETLY)
		MESSAGE(STATUS "Found LibPugiXml: ${LIBPUGIXML_LIBRARY}")
	ENDIF()
ELSE()
	IF(LibPugiXml_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find pugixml")
	ENDIF()
ENDIF()
